Dashboard development
MistySOM/MistyVision-Dashboard pull request #10
Opened 2024-02-26 22:54 UTC by victorwlyu321

Includes modification in HTML code that styles and displays live json message data.
Includes new .css and .js files for MistyVision Dashboard.

2024-02-26 23:31 UTC, matinlotfali requested changes
I have some change suggestions that @victor12321123 can address.

2024-02-26 23:31 UTC, matinlotfali commented on dashboarddata.js
> +            const timePortion = timestamp.split('T')[1].split('.')[0];
Where is this being used?

2024-02-26 23:31 UTC, matinlotfali commented on dashboarddata.js
> +                });
If the implementation is correct, the time should show the current time. But it is showing noon, instead of 3 pm.

2024-02-26 23:31 UTC, matinlotfali commented on dashboardstyle.css
> +
`rainbow` and `marquee` do not seem to be used in the HTML. I recommend removing it from CSS.

2024-02-26 23:31 UTC, matinlotfali commented on dashboardstyle.css
> +}
should be removed

2024-02-26 23:31 UTC, matinlotfali commented on dashboardstyle.css
> +}
should be removed

2024-02-26 23:31 UTC, matinlotfali commented on dashboardstyle.css
> +}
should be removed

2024-02-26 23:31 UTC, matinlotfali commented on dashboardstyle.css
> +}
should be removed

2024-02-26 23:31 UTC, matinlotfali commented on index.html
> +    <link rel="stylesheet" href="dashboardstyle.css">
Let's add a `<!-- MistyVision Dashboard CSS -->` on top of this line.

2024-02-26 23:31 UTC, matinlotfali commented on dashboarddata.js
> +console.log()
Useless line. Please remove

2024-02-26 23:31 UTC, matinlotfali commented on index.html
> +      <script src="dashboarddata.js"></script>
I would recommend moving this line to the `<head>`

2024-03-04 18:35 UTC, victorwlyu321 commented on dashboarddata.js
> +            const timePortion = timestamp.split('T')[1].split('.')[0];
It's for parsing through the Json message dictionary to get each of the data we want to display live

2024-03-08 01:20 UTC, matinlotfali approved these changes

2024-03-08 20:13 UTC, merged